### ISSUE TITLE
Event service integration test flake

### ISSUE THREAD

**Issue by richardcase** [weaveworks/reignite#115]
**What happened:**
The "integration" tests for the event service aren't very stable and often have to be re-run as we get an error:

```
=== RUN   TestEventService_Integration
    event_service_test.go:29: creating subscribers
    event_service_test.go:61: subscribers waiting for events
    event_service_test.go:58: finished publishing events
    event_service_test.go:94: rpc error: code = Canceled desc = context canceled
--- FAIL: TestEventService_Integration (0.01s)
```

**What did you expect to happen:**
I expect them to pass consistently

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- reignite version:
- OS (e.g. from `/etc/os-release`):

**Comment by yitsushi** [comment]
I did not see integration test failures for it. Can you link a failed build please?
