### ISSUE TITLE
Implement initial vmspec deletion plan (measure, plan, act

### ISSUE THREAD

**Issue by richardcase** [weaveworks/reignite#65]
**Describe the solution you'd like:**
A "plan" is needed with associated steps to delete a microvm from the spec.

**Why do you want this feature:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by mnowster** [comment]
- [ ] things

**Comment by richardcase** [comment]
- [ ] Decide on whether to refactor measurements to a separate entity for reuse
- [ ] Add `delete interface` to network service
- [ ] Add `delete network interface` step
- [ ] Add `delete file` step
- [ ]  Add `delete firecracker vm` step
- [ ] Add `unmount image` to image service
- [ ] Add `delete volume` step
- [ ] Create the `delete microvm` plan
- [ ] Call delete plan from microvm reconciliation loop
- [ ] Create event definitions for success and failure
- [ ] On error publish failure event and mark for retry
- [ ] On success publish event
